title: F de Física
description: Hola
theme: just-the-docs



logo: "/assets/images/ferabyss-letras1.png"
favicon_ico: "/assets/images/ferabyss-logo.jpg "

math: katex

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  nota:
    title: Nota
    color: purple


defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
    values:
      layout: "default"
