title: F de Física
description: Hola
theme: just-the-docs
color_scheme: foo


logo: "/assets/images/ferabyss letras1.png"
favicon_ico: "/assets/images/ferabyss logo.png"

math: katex


  
callouts:
  nota:
    title: Nota
    color: purple

defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
    values:
      layout: "default"
